spring.application.name=liverpool-orders-api
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/liverpool}
server.port=8080
mockapi.base-url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1